//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DigitalWareEntities : DbContext
    {
        public DigitalWareEntities()
            : base("name=DigitalWareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FacturaProducto> FacturaProducto { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
    
        public virtual ObjectResult<FacturaProductos> ObtenerFacturaProductos(Nullable<int> facturaId)
        {
            var facturaIdParameter = facturaId.HasValue ?
                new ObjectParameter("FacturaId", facturaId) :
                new ObjectParameter("FacturaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacturaProductos>("ObtenerFacturaProductos", facturaIdParameter);
        }
    
        public virtual ObjectResult<Facturas> ObtenerFacturas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Facturas>("ObtenerFacturas");
        }
    }
}
