//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage
{
    using System;
    
    public partial class Facturas
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string ClienteNombre { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
