//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage
{
    using System;
    
    public partial class FacturaProductos
    {
        public int Id { get; set; }
        public Nullable<int> FacturaId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string ProductoNombre { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> ValorTotal { get; set; }
    }
}
